<h1 align="center"> Homework4 My first Neural Network </h1>
Class: CS3210 Machine Learning

Professor: Feng Jiang

Created on: 4/1/2024  
Author: Ling Thang

Due Date: 4/5/2024

<h1 align="center">Assignment Description </h1>

(Only NumPy and data visualization packages are allowed.)
1. Read the demo code posted of simple NN in requirement.
2. Trains the NN more than 1,000 times and observe the change of the loss value. 
3. Implement a “3-6-2” network ( demo code 8_NN_2layer.py can be helpful) to fit the following data:  

```python
X=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0]], dtype=float) 
y=np.array([[0,1],[1,0],[0,1],[1,0],[0,1],[1,0],[0,1]], dtype=float)
```

4. What are the dimension of weight matrix 1 and weight matrix 2? (4pts)
5. Test the following sample and write down the predicted y values for it. (4 pts)
Testing sample one: X1 = [1, 1, 1]    y_pred = ?
6. Could you guess what is the meaning of y1 and y2 (first and second value in the label value for each sample)? (2 pts)
 
 

# Step 1: 
## Importing the required libraries
`Only NumPy and data visualization packages are allowed`

In [4]:
import numpy as np

# Training data: X - Input data (7 samples, 3 features), y - Output data (7 samples, 2 classes)
X=np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0]], dtype=float) 
y=np.array([[0,1],[1,0],[0,1],[1,0],[0,1],[1,0],[0,1]], dtype=float)

# Activation function
def sigmoid(s):
    return 1/(1+np.exp(-s))

# Derivative of activation function
def sigmoid_derivative(d):
    return d*(1-d)


## Function Description

The sigmoid function is a commonly used activation function in neural networks. It squashes the input values to a range between 0 and 1. The sigmoid function is defined as:

$$
\text{sigmoid}(s) = \frac{1}{1 + e^{-s}}
$$

where \( s \) is the input value.

```python
def sigmod(s):
    return 1 / (1 + np.exp(-s))
```

## Explanation for use 

given the dataset for the assignment, a Sigmoid Function which transforms the input value to a range between 0 and 1 is used.

## Sigmoid Derivative

$$
\text{sigmoid}'(s) = \text{sigmoid}(s) \times \left(1 - \text{sigmoid}(s)\right)
$$

```python
def sigmoid_derivative(d):
    return d * (1 - d)
```

# Step 2: 
## Neural Network Class
### Network Architecture
Following the specification of the assignment the Neural Network will Implement a "3-6-3" Network

### 3-6-2 Network
* Input Layer: 3 Neurons
* Hidden Layer: 6 Neurons
* Output Layer: 2 Neurons


In [2]:
class NeuralNetwork: 
    def __init__(self, x, y):
        self.input = x
        self.y = y
        self.output = np. zeros(y.shape)
        # 6 nodes in the hidden layer
        self.weights1 = np.random.rand(self.input.shape[1],6) 
        # 2 nodes in the output layer
        self.weights2 = np.random.rand(6,2) 

    def feedForward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
    
    def backprop(self): 
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -
        self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*
        sigmoid_derivative(self.output),
        self.weights2.T)*
        sigmoid_derivative(self.layer1))
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedForward()
        self.backprop()

# Training the Neural Network on 2000 iterations

In [3]:
NN = NeuralNetwork(X,y)
for i in range(2000): 
    if i % 200 == 0:
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedForward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedForward())))) # mean sum squared loss
        print ("\n")
        
NN.train(X, y)


for iteration # 0

Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]]
Actual Output: 
[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]
Predicted Output: 
[[0.72993715 0.77552145]
 [0.78325311 0.82266203]
 [0.7585346  0.80595597]
 [0.8047404  0.8456068 ]
 [0.77923657 0.82456305]
 [0.81861603 0.85818179]
 [0.80159103 0.84735921]]
Loss: 
0.33902622578112374


for iteration # 200

Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]]
Actual Output: 
[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]
Predicted Output: 
[[0.72993715 0.77552145]
 [0.78325311 0.82266203]
 [0.7585346  0.80595597]
 [0.8047404  0.8456068 ]
 [0.77923657 0.82456305]
 [0.81861603 0.85818179]
 [0.80159103 0.84735921]]
Loss: 
0.33902622578112374


for iteration # 400

Input : 
[[0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]]
Actual Output: 
[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0

# Visualizing with Matplotlib, Seaborn, and Tensorflow

In [ ]:
# Data Visualization Packages
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

